
package br.inatel.dm112.client.mail.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-31T15:57:03.543-03:00
 * Generated source version: 3.1.5
 * 
 */
public final class MailImpl_MailImplPort_Client {

    private static final QName SERVICE_NAME = new QName("dm112", "mailService");

    private MailImpl_MailImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MailService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MailService ss = new MailService(wsdlURL, SERVICE_NAME);
        MailImpl port = ss.getMailImplPort();  
        
        {
        System.out.println("Invoking sendMail...");
        java.lang.String _sendMail_arg0 = "";
        java.lang.String _sendMail_arg1 = "";
        java.lang.String _sendMail_arg2 = "";
        byte[] _sendMail_arg3 = new byte[0];
        br.inatel.dm112.client.mail.stub.MailStatusResponse _sendMail__return = port.sendMail(_sendMail_arg0, _sendMail_arg1, _sendMail_arg2, _sendMail_arg3);
        System.out.println("sendMail.result=" + _sendMail__return);


        }

        System.exit(0);
    }

}
