package br.inatel.dm112.client.mail.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-31T15:57:03.698-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "dm112", name = "MailImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface MailImpl {

    @WebMethod
    @RequestWrapper(localName = "sendMail", targetNamespace = "dm112", className = "dm112.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "dm112", className = "dm112.SendMailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.inatel.dm112.client.mail.stub.MailStatusResponse sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        byte[] arg3
    );
}
