
package br.inatel.dm112.client.billet.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-31T15:24:03.400-03:00
 * Generated source version: 3.1.5
 * 
 */
public final class BilletImpl_BilletImplPort_Client {

    private static final QName SERVICE_NAME = new QName("dm112", "billetService");

    private BilletImpl_BilletImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BilletService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BilletService ss = new BilletService(wsdlURL, SERVICE_NAME);
        BilletImpl port = ss.getBilletImplPort();  
        
        {
        System.out.println("Invoking generateBillet...");
        java.lang.String _generateBillet_arg0 = "";
        java.lang.String _generateBillet_arg1 = "";
        br.inatel.dm112.client.billet.stub.BilletGenResponse _generateBillet__return = port.generateBillet(_generateBillet_arg0, _generateBillet_arg1);
        System.out.println("generateBillet.result=" + _generateBillet__return);


        }

        System.exit(0);
    }

}
