package br.inatel.dm112.client.billet.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-31T15:24:03.515-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "billetService", 
                  wsdlLocation = "http://localhost:8080/UtilityDM112/soap/billetservices?wsdl",
                  targetNamespace = "dm112") 
public class BilletService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("dm112", "billetService");
    public final static QName BilletImplPort = new QName("dm112", "BilletImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/UtilityDM112/soap/billetservices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BilletService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/UtilityDM112/soap/billetservices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BilletService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BilletService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BilletService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BilletService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BilletService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BilletService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BilletImpl
     */
    @WebEndpoint(name = "BilletImplPort")
    public BilletImpl getBilletImplPort() {
        return super.getPort(BilletImplPort, BilletImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BilletImpl
     */
    @WebEndpoint(name = "BilletImplPort")
    public BilletImpl getBilletImplPort(WebServiceFeature... features) {
        return super.getPort(BilletImplPort, BilletImpl.class, features);
    }

}
